name: platform-mts-build

on: 
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
  build-platform-mts-amd64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/service-build.yml@main
    with:
      APP_PROJECT: ./src/platform-mts.csproj
      NUGET_PROJECT: ./src_pluginBase/pluginBase.csproj
      OUTPUT_DIR: /var/spacedev/tmp/platform-mts
      NUGET_STAGING_DIRECTORY: /var/spacedev/nuget/mts
      NUGET_FILE_PREFIX: Microsoft.Azure.SpaceSDK.PlatformServices.MessageTranslationService.Plugins
      ANNOTATION: azure-orbital-space-sdk-platform-mts.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: amd64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  build-platform-mts-arm64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/service-build.yml@main
    with:
      APP_PROJECT: ./src/platform-mts.csproj
      NUGET_PROJECT: ./src_pluginBase/pluginBase.csproj
      OUTPUT_DIR: /var/spacedev/tmp/platform-mts
      NUGET_STAGING_DIRECTORY: /var/spacedev/nuget/mts
      NUGET_FILE_PREFIX: Microsoft.Azure.SpaceSDK.PlatformServices.MessageTranslationService.Plugins
      ANNOTATION: azure-orbital-space-sdk-platform-mts.yaml
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
      ARCHITECTURE: arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}